# Generated by Django 4.2.5 on 2025-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TODO', '할 일'), ('DOING', '진행 중'), ('DONE', '완료')], default='TODO', help_text='현재 작업 상태를 선택해주세요.', max_length=5, verbose_name='상태')),
                ('priority', models.PositiveIntegerField(choices=[(1, '낮음'), (2, '보통'), (3, '높음')], default=2, help_text='우선순위를 선택해주세요 (1=낮음, 2=보통, 3=높음).', verbose_name='우선순위')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
